### ISSUE TITLE
How to get custom hashtag

### ISSUE THREAD

**Issue by ucelme** [gokhanmandaci/HMTextView#1]
Hello. For example, I want to every time print custom hashtag. For example, current time. But when I try to use custom value in your demo, I get no hashtag inserted. For example:

    let time = "3"

    @IBAction func gokhanAction(_ sender: Any) {
        self.hmTextView.addLink(time, type: .hashtag, withReplacing: true)
    }

Happens nothing.

**Comment by gokhanmandaci** [comment]
Hello, thanks for the issues. 
There was a control that prevents the detection of links smaller than 3 characters. Now a new configuration parameter called "minimumLinkCharCount" which can be set after creating HMTextView.

Example: 
...
hmTextView.minimumLinkCharCount = 1
...
