### ISSUE TITLE
regex configuration parameter

### ISSUE THREAD

**Issue by ucelme** [gokhanmandaci/HMTextView#2]
Hello. Can you provide sample code how I can modify rerex to allow using numbers in hashtags? For some reasong I cannot use them now.

**Comment by gokhanmandaci** [comment]
Hello, I developed this HMTextView for my own project. And in this project, we do not allow links to start with numbers. So the ability to detect links that are starting with numbers was missing. Now I added a configuration parameter for this issue. I hope this would help.

Example: 
...
hmTextView. allowLinksStartWithNumber = true
...

**Comment by ucelme** [comment]
Thank you very much for answer! But I also need to resolve : sign to show time correct. For example, I want to ad hastag with 01:33. How I can resolve : symbol? Can you help me with this?

**Comment by gokhanmandaci** [comment]
Let's try another regex.

This one is the default regex for HMTextView.
> "(?<=\\s|^)([@#][\\p{L}\\d]+[._]\\p{L}+|[#@][\\p{L}\\d]*)(?=[']\\p{L}+|[.,;:?!](?:\\s|$)|\\s|$)"

After "(?<=\\s|^)([@#][\\p{L}\\d]+" this part, there is a set of allowed characters. 
Lets change "[._]" this one to "[._:]". 

After that part, we allow only letters with "\\p{L}" this. 
Lets change "\\p{L}" this one to "[\\p{L}\\d]".

Finally, we have this one:
> "(?<=\\s|^)([@#][\\p{L}\\d]+[._:][\\p{L}\\d]+|[#@][\\p{L}\\d]*)(?=[']\\p{L}+|[.,;:?!](?:\\s|$)|\\s|$)".

By adding the regex above as a configuration parameter, you will be able to detect times like 
> "01:33".

> Example:
> hmTextView. regex = "(?<=\\s|^)([@#][\\p{L}\\d]+[._:][\\p{L}\\d]+|[#@][\\p{L}\\d]*)(?=[']\\p{L}+|[.,;:?!](?:\\s|$)|\\s|$)"

By the way, I'm using [regex101](https://regex101.com/) to test my regex. 👍
