### ISSUE TITLE
Failed to open URL hash

### ISSUE THREAD

**Issue by ucelme** [gokhanmandaci/HMTextView#5]
Hello. Thanks for your support. 

I implemented all the requirments for HMTextView as it's in Example project, but when I click on hastag I get Failed to open URL hash:12:12: Error Domain=NSOSStatusErrorDomain Code=-10814 "(null)" UserInfo={_LSLine=247, _LSFunction=-[_LSDOpenClient openURL:options:completionHandler:]}

And delegate method not works in some reason. Can you help me what I can do to resolve this issue?

**Comment by gokhanmandaci** [comment]
I searched for the error and it seems your URLSchemes are wrong. You may need to add the scheme for the URL you want to open.

I am not getting the error in the example project when I try the links with times. So if you can share the code, I can try to check why delegate methods not called.

**Comment by ucelme** [comment]
I found a problem. If I use UITextViewDelegate protocol and add to viewDidLoad         hmTextView.delegate = self, HMTextView not works on clicking links. Can I use UITextViewDelegate and HMTextViewProtocol simultaneously? And also use         hmTextViewDelegate = self and  hmTextView.delegate = self in viewDidLoad? Or what I should do?

**Comment by gokhanmandaci** [comment]
Yes, there is a limitation with the delegate methods. If you want to use HMTextView delegate you **shouldn't** use TextView delegate. HMTextView has it's own protocol which has the following methods:

> // HMTextView Specific Methods (Available)
> func links(hashtags: [String], mentions: [String]) // returns the links in the textview
> func clicked(on link: String, type: HMType) // called when clicking on links
> func readyToEnter(link_with type: HMType) // called when you are about to enter a link
> func stoppedEntering(link_with type: HMType) // called when you stop entering a link
> func charLimitReached() // called when specified character limit reached for textview
> func charLimitAvailable() // called when you entered a character and the character limit will not be reached
> func chars(_ written: Int, _ remained: Int) // returns characters while you are writing

> // TextView Common Methods (Available)
> func shouldBeginEditing(_ textView: UITextView) // for textViewShouldBeginEditing
> func didEndEditing(_ textView: UITextView) // for textViewDidEndEditing
> func didChange(_ textView: UITextView) // for textViewDidChange

> // Not Implemented TextView Methods (Not Available)
> func textViewDidBeginEditing(_ textView: UITextView)
> func textViewDidChangeSelection(_ textView: UITextView)
> func textViewShouldEndEditing(_ textView: UITextView) -> Bool

I'm planning to refactor the code and add support for "Not Implemented TextView Methods". But if you want to use them, I can release another version. Otherwise, you can use "Available" methods.

**Comment by ucelme** [comment]
And what for UITextViewDelegate method:
func textView(UITextView, shouldChangeTextIn: NSRange, replacementText: String) -> Bool

Can I use it with HMTextView delegate?

**Comment by gokhanmandaci** [comment]
Unfortunately, not for now. Some dependent methods like detecting links and getting the cursor positions, handled in "shouldChangeTextIn" method. So I think it will cause some unexpected errors. But I'll make another workaround before the main release.

**Comment by gokhanmandaci** [comment]
I implemented all the methods on version 0.2.0. 👍

**Comment by ucelme** [comment]
Thank you very much for your great work!

How you tested the next method?

func shouldChangeTextIn(_ textView: UITextView,
                        _ range: NSRange,
                        _ replacementText: String,
                        _ returning: Bool)

which should correspond:

func textView(_ textView: UITextView, 
    shouldChangeTextIn range: NSRange, 
       replacementText text: String) -> Bool

In my case I cannot make it work.

And it will be great to make all delegate methods optional as it was before. In new version I should implement each of this method to conform the HMTextViewProtocol protocol.

**Comment by gokhanmandaci** [comment]
You're welcome. Thank you for your support.
All methods will be optional with the 0.2.1 version. 

About "func textView(_ textView: UITextView,
shouldChangeTextIn range: NSRange,
replacementText text: String) -> Bool":

HMTextView used this method for "detecting links", getting "cursor point", etc. There are two returning lines in this method. Just before these tho lines, it calls our "shouldChangeTextIn" delegate method and you can reach textView, range, replacement text, and returning value. 

These two returning points are:

1)This method returns Bool, so HMTextView used this bool value when checking character limit and backspace. If the character limit is reached and the next character is not "backspace" this returning value will be false and you will not be able to write more.

2) If the char limit is not set, the method returns true.

So if you want to use this method for another purpose, please tell me about it because it will be so useful for improving this class. I would be very happy to find a solution for your case.

**Comment by ucelme** [comment]
In my case I use this method to make first line of textview as bold. This is my implementation:

    func shouldChangeTextIn(_ textView: UITextView, _ range: NSRange, _ replacementText: String, _ returning: Bool) {
        let textAsNSString = hmTextView.text as NSString
        let replaced = textAsNSString.replacingCharacters(in: range, with: replacementText) as NSString
        let boldRange = replaced.range(of: "\n")
        if boldRange.location <= range.location {
            self.hmTextView.typingAttributes = self.headerAttributes
        } else {
            self.hmTextView.typingAttributes = self.bodyAttributes
        }
    }

    let headerAttributes = [NSAttributedString.Key.font : UIFont.preferredFont(forTextStyle: UIFont.TextStyle.body)]
    let bodyAttributes = [NSAttributedString.Key.font : UIFont.preferredFont(forTextStyle: UIFont.TextStyle.headline)]

**Comment by gokhanmandaci** [comment]
First of all, we are looking for this character "\n". 

If a user does not press return key - and in our case, we don't have it, we have "@" and "#" characters - we will not have "\n" character. So we won't be able to identify the new line while writing the text. For this purpose, we need to change the keyboard type from "Twitter" to another one. 

Also if when assigning text to the text view, we need "\n" character to identify heading. 
So, although the user assigned a long text and make the text multiple lines, we cannot identify heading.

If there is another way of identifying heading and body, we can try it but for our case I will search for "\n" character.

Let's create this function. We can call it whenever we need it. When adding links, assigning predefined content, etc.

```
private func makeHeading(for textView: UITextView) {
    let textAsNSString = textView.text as NSString
    let newAttributedText = NSMutableAttributedString(attributedString: textView.attributedText)
    var boldRange = NSRange(location: 0, length: textAsNSString.length)
    if let indexOfNewLine = textView.text.firstIndex(of: "\n")?.utf16Offset(in: textView.text) {
        print(indexOfNewLine)
        boldRange = NSRange(location: 0, length: indexOfNewLine)
    }
    newAttributedText.addAttribute(NSAttributedString.Key.font, value: UIFont.preferredFont(forTextStyle: UIFont.TextStyle.headline), range: boldRange)
        textView.attributedText = newAttributedText
}
```

And add two delegate methods "shouldChangeTextIn" and "didEndEditing"

```
func shouldChangeTextIn(_ textView: UITextView, _ range: NSRange, _ replacementText: String, _ returning: Bool) {
    print("HMTextView should change text in: \(textView.text ?? "")\nwith range: \(range)\nwith replacement text:\(replacementText)\nreturning: \(returning)")
    makeHeading(for: textView)
}
func didEndEditing(_ textView: UITextView) {
    print("HMTextView did end editing: \(textView.text ?? "")")
    makeHeading(for: textView)
}
```

With these methods, I was able to make the heading.

**Comment by ucelme** [comment]
Thank you very much for help. It works. =)
