### ISSUE TITLE
HMTextView initialize

### ISSUE THREAD

**Issue by ucelme** [gokhanmandaci/HMTextView#6]
I try to implement HMTextView, but it initialize only when I start editing text. When I just open TextView, HMTextView doesn't initialize.

![ezgif com-video-to-gif-4](https://user-images.githubusercontent.com/46785623/82056354-8361b400-96ca-11ea-8af6-ab40c727929f.gif)

How I can resolve this issue and make HMTextView initialize when I just open TextView without start typing.

**Comment by gokhanmandaci** [comment]
It looks like a bug, I'll try to create the case and look for a solution. Maybe we need a trigger for the texts assigned in the runtime.

**Comment by gokhanmandaci** [comment]
Hello, I updated the example project you can check it. The link must be assigned after the initialization of the text view. I think adding links flow was the problem.
